=== openpodcast/api/src/schema/anchor/playsByEpisode.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "provider": {
      "type": "string"
    },
    "version": {
      "type": "number"
    },
    "retrieved": {
      "type": "string"
    },
    "meta": {
      "type": "object",
      "properties": {
        "show": {
          "type": "string"
        },
        "endpoint": {
          "type": "string"
        }
      },
      "required": [
        "show",
        "endpoint"
      ]
    },
    "range": {
      "type": "object",
      "properties": {
        "start": {
          "type": "string"
        },
        "end": {
          "type": "string"
        }
      },
      "required": [
        "start",
        "end"
      ]
    },
    "data": {
      "type": "object",
      "properties": {
        "stationId": {
          "type": "number"
        },
        "kind": {
          "type": "string"
        },
        "parameters": {
          "type": "object",
          "properties": {
            "timeRange": {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "timeInterval": {
              "type": "number"
            },
            "limit": {
              "type": "number"
            }
          },
          "required": [
            "timeRange",
            "timeInterval",
            "limit"
          ]
        },
        "data": {
          "type": "object",
          "properties": {
            "rows": {
              "type": "array",
              "items": {
                "type": "array",
                "items": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string"
                  },
                  {
                    "type": "number"
                  }
                ],
                "additionalItems": false
              }
            },
            "columnHeaders": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string"
                  },
                  "isDateTime": {
                    "type": "boolean"
                  },
                  "labelKey": {
                    "type": "string"
                  }
                },
                "required": [
                  "type"
                ]
              }
            },
            "labels": {
              "type": "object",
              "properties": {
                "EpisodeTitle": {
                  "type": "object",
                  "properties": {
                    "0": {
                      "type": "string"
                    },
                    "1": {
                      "type": "string"
                    },
                    "2": {
                      "type": "string"
                    },
                    "3": {
                      "type": "string"
                    },
                    "4": {
                      "type": "string"
                    },
                    "5": {
                      "type": "string"
                    },
                    "6": {
                      "type": "string"
                    },
                    "7": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7"
                  ]
                }
              },
              "required": [
                "EpisodeTitle"
              ]
            }
          },
          "required": [
            "rows",
            "columnHeaders",
            "labels"
          ]
        }
      },
      "required": [
        "stationId",
        "kind",
        "parameters",
        "data"
      ]
    }
  },
  "required": [
    "provider",
    "version",
    "retrieved",
    "meta",
    "range",
    "data"
  ]
}

=== openpodcast/api/fixtures/anchorPlaysByEpisode.json
{
  "provider": "anchor",
  "version": 1,
  "retrieved": "2023-05-05T16:18:21.247168",
  "meta": {
    "show": "123abcde",
    "endpoint": "playsByEpisode"
  },
  "range": {
    "start": "2023-05-01",
    "end": "2023-05-04"
  },
  "data": {
    "stationId": 98765432,
    "kind": "playsByEpisode",
    "parameters": {
      "timeRange": [
        1682899200,
        1683158400
      ],
      "timeInterval": 86400,
      "limit": 3
    },
    "data": {
      "rows": [
        [
          1682899200,
          "0",
          1
        ],
        [
          1682899200,
          "1",
          1
        ],
        [
          1682899200,
          "2",
          1
        ],
        [
          1682985600,
          "3",
          3
        ],
        [
          1682985600,
          "4",
          2
        ],
        [
          1682985600,
          "5",
          2
        ],
        [
          1683072000,
          "6",
          2
        ],
        [
          1683072000,
          "7",
          2
        ],
        [
          1683072000,
          "5",
          2
        ],
        [
          1683158400,
          "5",
          5
        ],
        [
          1683158400,
          "6",
          2
        ],
        [
          1683158400,
          "7",
          2
        ]
      ],
      "columnHeaders": [
        {
          "name": "Time (UTC)",
          "type": "integer",
          "isDateTime": true
        },
        {
          "labelKey": "EpisodeTitle",
          "type": "string"
        },
        {
          "name": "Plays",
          "type": "integer"
        }
      ],
      "labels": {
        "EpisodeTitle": {
          "0": "Title 0",
          "1": "Title 1",
          "2": "Title 2",
          "3": "Title 3",
          "4": "Title 4",
          "5": "Title 5",
          "6": "Title 6",
          "7": "Title 7"
        }
      }
    }
  }
}
